runtime: java11

service: default

instance_class: F2

handlers:
  - url: /api/admin/upsert
    script: unused

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 100